### ISSUE TITLE
Update 'Stake ADX' pop-up with 2021 rewards & add tooltip on APY on Staking portal

### ISSUE THREAD

**Issue by NadiaIv** [AdExNetwork/adex-staking#102]
Could we please update following info in the Stake ADX pop-up when you select Tom:

1. Update highlighted text to read: There is an additional incentive reward of 20 million ADX to be distributed by the end of 2021.

<img width="699" alt="Screenshot 2021-02-04 at 15 43 17" src="https://user-images.githubusercontent.com/48917288/106920454-63b46500-670b-11eb-9b94-2421cf2ac63e.png">

2. Add a tooltip on Pool APY to say: ⚠️Warning: the annual percentage yield is calculated based on the current staked amount. With more ADX staked, the amount will decrease: [Read more](https://www.adex.network/blog/new-token-economics-and-staking/).

3. Make them tick two boxes instead of the current 1, replace it with these 2:

[ ] I am familiar with the AdEx [Terms and Conditions](https://www.adex.network/tos/) and the staking conditions.
[ ] I understand that Pool Tom has a [30 day unbond period](https://help.adex.network/hc/en-us/articles/360019463419-Does-Validator-Pool-Tom-have-a-lock-up-period-).

**Comment by rori4** [comment]
I think this is finished with the new staking version
![image](https://user-images.githubusercontent.com/22402693/113414581-fbf65f80-93c5-11eb-99bb-4ef03d16dd36.png)
