### ISSUE TITLE
Add a new box: 'New to staking' on staking portal

### ISSUE THREAD

**Issue by NadiaIv** [AdExNetwork/adex-staking#103]
On the staking portal [main page (pools)](https://staking.adex.network/#/): make Subscribe to newsletter box smaller and add another box underneath it:

New to staking? [Learn more](https://help.adex.network/hc/en-us/articles/360019465979-New-to-staking-A-summary-of-all-you-need-to-know)

<img width="1428" alt="staking home" src="https://user-images.githubusercontent.com/48917288/107233226-a1becb00-6a22-11eb-9844-f4f9e57367bb.png">

Assigning Ally for now as this would need design

**Comment by alesinka** [comment]
![image](https://user-images.githubusercontent.com/24762344/107484489-2a587b00-6b8b-11eb-93fa-0d6083acbbcb.png)

**Comment by NadiaIv** [comment]
Hi Ally,

That looks good! We'd like to just change the text a little (not sure if this applies to you in any way or it's for Ran):

from 'Learn more' to 'Learn the basics'

Thanks!

**Comment by alesinka** [comment]
Yeah, there is enough space for longer text, too, so you can put it instead.
