### ISSUE TITLE
Migration modal

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-staking#108]
## Summary

The migration UI will consist of 3 elements:

1. Migrate button on each bond (does not need design)
2. Modal to confirm (does not need design, we'll use the same modal as "new bond"); this should have a checkbox for "[x] Claim pending rewards and stake them (costs more gas)"; if this is checked, we also claim rewards, transfer them to the StakingMigrator, and pass the amount as `extraAmount`; and another checkbox for "[ ] Also stake X ADX currently on your wallet", only active if you have ADX on your wallet
3. modal to prompt users to migrate their bonds - this will need design - needs to look important (like the Stremio upgrade modal that we did a while back). Will have to buttons: "not now" and "migrate". Will always appear if you have unmigrated bonds. Clicking "migrate" would pop up the modal to confirm, unless there's more than 1 bond, in which case it goes to Bonds.

**Comment by alesinka** [comment]
![image](https://user-images.githubusercontent.com/24762344/111318525-cf281580-866d-11eb-8d96-e8a1e1444bd3.png)
