### ISSUE TITLE
Update Validator Stats page on Staking portal

### ISSUE THREAD

**Issue by NadiaIv** [AdExNetwork/adex-staking#117]
Here's what needs changing (see screenshot below):

**1. Under Rewards**

Change from: 
The "Validator Tom" pool will distribute its fee earnings proportionally to each staker. The fee earnings will be 7% of the total volume, which you can track on our Explorer. There is an additional incentive reward of 7 million ADX to be distributed by the end of 2020.

To:
The DAI fee earnings of 7% of the total volume, which you can track on our Explorer, will be used for ADX buybacks. There is an incentive reward of 20 million ADX to be distributed by the end of 2021.

**2. Lock up period**

Change both mentions from 30 days to 20 days

<img width="1432" alt="Screenshot 2021-04-26 at 13 27 34" src="https://user-images.githubusercontent.com/48917288/116075978-ed812800-a693-11eb-8e62-7d6d154c3798.png">

**Comment by IvoPaunov** [comment]
https://github.com/AdExNetwork/adex-staking/commit/09f666c4ef9babed39351653607e622dc76fad33
