### ISSUE TITLE
Logical separation between user data and total data

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-staking#34]
User data is:
* your ADX balance (total)
   * your ADX staked
   * available on wallet
* your rewards - ADX, DAI, total in USD; show tooltip explaienrs for both
  * show a `+` icon between ADX/DAI amounts to signify user earned both, and it's not an either-or
  * if we add more reward currencies in the future (eg other stables) we can just show the summarized USD amount
  * ... or alternatively, retain the same design but show total stablecoin amount instead of DAI amount
* your bonds

While global data is:
* Total ADX staked
* any validator data (volume, etc.)

**Comment by alesinka** [comment]
Rewards info + pools data updated
![Pools – rewards](https://user-images.githubusercontent.com/24762344/92582022-1b4a6580-f299-11ea-8227-95fe2bcec213.png)
