### ISSUE TITLE
UI for multiple pools, including "Coming soon"

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-staking#42]
* Show weekly % earn besides APY
* Consider a tooltip that explains compounding can increase this
* Each pool should show it's TLV in it's native currency and USD

Similar to #33

**Comment by alesinka** [comment]
![Pools](https://user-images.githubusercontent.com/24762344/93060932-8d48f300-f67b-11ea-82a6-fefcaa2e0fe3.png)
