### ISSUE TITLE
Pool cards design: indicate APY, sustainability, lockup

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-staking#46]
* show sustainability raiting with a link to a full explanation
* cards to show more earning info: daily earning, show whether the APY is fixed/dynamic
* show "dynamic APY" or "variable APY" vs "fixed APY"/"stable APY" vs "predictable APY"
* cards to show lockup period

**Comment by alesinka** [comment]
![image](https://user-images.githubusercontent.com/24762344/93569681-8cc19c80-f99a-11ea-93c5-b30da55fb2ff.png)

**Comment by Ivshti** [comment]
Closing this despite it lacking sustainability - it's no longer a questionable point since the APY is relatively tame
