### ISSUE TITLE
Staking Landing page Texts 

### ISSUE THREAD

**Issue by dmngdsm** [AdExNetwork/adex-staking#50]
![Screenshot 2020-09-23 at 11 43 37](https://user-images.githubusercontent.com/15030734/93989012-0fc76600-fd92-11ea-9b23-ef9f48e26cee.png)

**H1:** Earn rewards by staking ADX
**Text box:** Мaximize your ADX holdings by staking, rather than just let them sit in your wallet! By staking your assets you provide stability to the AdEx Platform and earn additional ADX as rewards in return. You can claim rewards right away or re-stake for compounding interest. 

**Button:** Stake now
**Button:** FAQ

**Disclaimer:** ⚠️Warning: the annual percentage yield is calculated based on the current staked amount. With more ADX staked, the amount will decrease: Read more.

![Screenshot 2020-09-23 at 12 00 11](https://user-images.githubusercontent.com/15030734/93990888-56b65b00-fd94-11ea-8459-01169e2eb0bb.png)

**H1:** How to start
**Step 1:** Get ADX
**Step 1 text:** Buy [ADX tokens](https://help.adex.network/hc/en-us/articles/360015933099-How-can-I-get-ADX-tokens-List-of-exchanges-) or fund your wallet with ADX and some ETH for gas. 

**Step 2:** Select a pool
**Step 2 text:** Choose from the available pools to stake your ADX to. Currently there's only one pool available but soon there will be more added.

**Step 3:** Earn ADX
**Step 3 text:** Check your dashboard to see accumulated rewards. You can claim them or re-stake them for compounding interest. 

**Gasless stake tooltip:** Coming soon

**Comment by rori4** [comment]
Adding some comments from Ivo here:
- gasless needs to be hidden 
- how to join icons are missing 
- by staking tokens needs to be “by staking adx”
- “Metamask account” needs to be changed to “Ethereum wallet”

**Comment by alesinka** [comment]
![image](https://user-images.githubusercontent.com/24762344/94009304-f1bb2f00-fdac-11ea-95ac-a289a8ff2c6b.png)

**Comment by rori4** [comment]
This has been implemented in https://www.adex.network/staking/
