### ISSUE TITLE
Make "Generated rewards" number animated

### ISSUE THREAD

**Issue by dmngdsm** [AdExNetwork/adex-staking#51]
![image](https://user-images.githubusercontent.com/15030734/94135543-4671af00-fe6c-11ea-9a38-477cd29e6d83.png)

Make this number grow all the time while user browses the website. Calculate the rate of how ADX rewards grow or just add 0.01$ each 5 seconds or whatever works, so that it triggers FOMO in users while browsing

**Comment by rori4** [comment]
this has been implemented
