### ISSUE TITLE
Design for email leadgen subscribe field on the Staking platform and landing page

### ISSUE THREAD

**Issue by dmngdsm** [AdExNetwork/adex-staking#56]
We need to include a simple yet eye-catching promotional leadgen form and add it to the staking landing page and the staking portal (not sure about the latter, but however the design is one). This is related to [this issue ](https://github.com/AdExNetwork/Marketing/issues/268)in Marketing .

To incentivize people to give us their emails we will run a promotion - 5 lucky subscribers will get 1000 ADX each. This is pretty good number for just giving your email address so it should be appealing and straightforward. 

The form itself will containing placeholder for email, Subscribe button and "I want AdEx Network to send me information about news and promotions"

The form has to be in a box or something and have a promotional heading: "Subscribe for AdEx News and win 5x1000 ADX!"

Can you please design the form so that it can "live" in a popup window too? It will be optimal if we test exit-intent popup but more important is to have the form on the landing page on first place.

**Comment by alesinka** [comment]
Design in Pools page: 
![image](https://user-images.githubusercontent.com/24762344/94834423-09cc2780-0419-11eb-96da-04a33173c3bf.png)

Design for the landing page (Hero title should be a bit moved up and modify the paragraph size to fit in 3 rows, so there is enough space for the E-mail box below the buttons @rori4 ):
![image](https://user-images.githubusercontent.com/24762344/94834590-38e29900-0419-11eb-8914-7f51faff0c58.png)

**Comment by rori4** [comment]
@alesinka can you please add the email icon here so I can start with this tomorrow

**Comment by alesinka** [comment]
![mail-awards](https://user-images.githubusercontent.com/24762344/94837021-60873080-041c-11eb-9feb-50613bcfa2cd.png)

**Comment by alesinka** [comment]
Here is an SVG, in case it is better than the PNG:

[mail-awards icon.zip](https://github.com/AdExNetwork/adex-staking/files/5313682/mail-awards.icon.zip)

**Comment by alesinka** [comment]
Also a design for the popup:
https://xd.adobe.com/view/e28bc88b-e8f6-4286-9231-5009769457bf-b7d8/screen/df70db10-dd8e-4583-807b-00e5e089373e

Button hover: PINK.
Background: Dark transparent overlay

Assets: 
[leadgen popup assets.zip](https://github.com/AdExNetwork/adex-staking/files/5327724/leadgen.popup.assets.zip)

**Comment by rori4** [comment]
Is this going to be a popup on exit intent or after some time? When will it be displayed @vanina-iv @dmngdsm

**Comment by dmngdsm** [comment]
I'd say an exit-intent after some time, say 5-10 seconds.
