### ISSUE TITLE
Lp pool card and modal

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-staking#60]
Purpose: Pool for liquidity providers
APY: dynamic

Card appearance should be like the Tom card, except:
* no gasless and no calculator
* short description "earn ADX by supplying liqudity on Uniswap, Sushiswap and Loopring"
* no unbond period 
* "Provide Liqudity" button instead of stake; when you click it you get a modal with 3 options: Uniswap, Sushiswap, Loopring
   * when you click on one of the options, you get redirected to the relevant page
   * there should also be a short explainer text (you will automatically start ADX rewards if you provide liquidity) and a warning (impermanent loss)

In "Staked ADX" (which should be renamed to just "Staked") there should be a new category, "Liquidity", that shows your current provided liquidity. Unlike the others, the entries in this one will show balance in ADX and the other currency of the market pair
Eg  "Uniswap    |    1000 ADX, 0.5 ETH". There would be an unstake button that redirects you to the relevant page

**Comment by alesinka** [comment]
![image](https://user-images.githubusercontent.com/24762344/95198969-c260e500-07e4-11eb-8163-b7f7e323108c.png)

**Comment by alesinka** [comment]
![image](https://user-images.githubusercontent.com/24762344/95296695-e4f50b80-0881-11eb-9c9a-31fc9706f82d.png)

**Comment by Ivshti** [comment]
closing in favor of #73
