### ISSUE TITLE
Popup "Stake your ADX"  after successfully upgrading your ADX

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-staking#62]
The AdEx upgrade modal should transform to "Sucess! You've upgraded your ADX" popup which also includes a suggestion to stake the ADX for added rewards

Even though this is the staking portal and the ability to stake is everywhere, a popup should help with the psychological appeal of staking

**Comment by Ivshti** [comment]
Here's an example of how aave does it, it looks nice
![app aave com_migration-portal_congratulations_expectedAaveBalance=937 28716583795083588015](https://user-images.githubusercontent.com/1247629/94986724-af8eac00-0569-11eb-9a0c-a03dadf7cd4e.png)

**Comment by alesinka** [comment]
Didn't want to copy it, but almost 👯
![Upgrade popup](https://user-images.githubusercontent.com/24762344/96240116-2fc10280-0fa9-11eb-9bbf-ac4ffd3b44ad.png)

**Comment by Ivshti** [comment]
@IvoPaunov this could be next after the translations
