### ISSUE TITLE
Update AdEx Staking Newsletter Subscribe Form

### ISSUE THREAD

**Issue by dmngdsm** [AdExNetwork/adex-staking#78]
As we finished the staking subscribe promo, we need to update forms accordingly. There are 3 forms currently - on the Landing Page (1), on the Dashboard (2) and on Exit Intent Popup (3).

1. 
![Screenshot 2020-11-02 at 16 35 11](https://user-images.githubusercontent.com/15030734/97880277-a55afb80-1d29-11eb-9091-e5fdac2f0e59.png)
2.
![Screenshot 2020-11-02 at 16 35 23](https://user-images.githubusercontent.com/15030734/97880271-a429ce80-1d29-11eb-9714-af45aad0c058.png)
3.
![Screenshot 2020-11-02 at 16 35 49](https://user-images.githubusercontent.com/15030734/97880267-a12ede00-1d29-11eb-9253-776acda801d3.png)

On 1 and 2 we change the text to:

Subscribe for AdEx News **for exclusive content** [bold is in yellow]

On 3 we change the text to: 

Subscribe for AdEx News  **and don't miss Staking tips and insights** [bold is in yellow]

On all forms we can remove the checkpoint that says:  "I agree to the promotional T&C" . The other one stays

**Comment by Ivshti** [comment]
Done and deployed
